### ISSUE TITLE
GPU OOM issue with per_device_train_batch_size=1 on A100 80G

### ISSUE THREAD

**Issue by Glupayy** [tulerfeng/Video-R1#15]
Hi! Thanks for the great work!

I am trying to reproduce the SFT result by running ``run_sft_video.sh`` script, but I encounter the OOM issue with the default settings in this script, using 4*A100 80G. Do you have any idea of the potential reason?  Thanks for any feedbacks!

```
[rank0]:   File "~/miniconda3/envs/video-r1/lib/python3.11/site-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 320, in forward
[rank0]:     attn_output = F.scaled_dot_product_attention(q, k, v, attention_mask, dropout_p=0.0)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 131.22 GiB. GPU 0 has a total capacity of 79.33 GiB of which 1.27 GiB is free. Process 149245 has 78.05 GiB memory in use. Of the allocated memory 54.83 GiB is allocated by PyTorch, and 22.41 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

**Comment by tulerfeng** [comment]
Have you adjust the max resolution and max frame in qwen vl utils?

Directly using native resolution in Qwen may cause OOM.

**Comment by tulerfeng** [comment]
The training setting should be set as follows:

```
IMAGE_FACTOR = 28
MIN_PIXELS = 4 * 28 * 28
MAX_PIXELS = 256 * 28 * 28
MAX_RATIO = 200

VIDEO_MIN_PIXELS = 128 * 28 * 28
VIDEO_MAX_PIXELS = 128 * 28 * 28
FRAME_FACTOR = 2
FPS = 2.0
FPS_MIN_FRAMES = 4
FPS_MAX_FRAMES = 16
```

**Comment by Glupayy** [comment]
OOM Problem solved by setting the resolution! Thank you!

Just for a check, is it normal for ``[h264 @ 0x55a20888a100] mmco: unref short failure`` to be printed during training? The training is still ongoing, but it seems to have a problem with decoding the video...


```
[h264 @ 0x55a20888a100] mmco: unref short failure
[h264 @ 0x5612ff112800] mmco: unref short failure
{'loss': 3.0491, 'grad_norm': 114.69791412353516, 'learning_rate': 9.91012756088133e-07, 'num_tokens': 1506971.0, 'mean_token_accuracy': 0.34750668704509735, 'epoch': 0.01}
{'loss': 2.0893, 'grad_norm': 72.10563659667969, 'learning_rate': 9.909161190568224e-07, 'num_tokens': 1521379.0, 'mean_token_accuracy': 0.4593222737312317, 'epoch': 0.01}
  1%|▊                                                                                              | 94/10348 [11:42<19:40:16,  6.91s/it][h264 @ 0x564b79a2a140] mmco: unref short failure
```

**Comment by tulerfeng** [comment]
This is just a warning. It is normal for qwen vl utils with the decord feature. Don't worry about it.

**Comment by bingo-G** [comment]
When I run run_grpo_vllm_qwen25vl.sh, the command I use is as follows: 
```
CUDA_VISIBLE_DEVICES="0,1,2,3" torchrun \
    --nproc_per_node="3" \
    --nnodes="1" \
    --node_rank="0" \
    --master_addr="127.0.0.1" \
    --master_port="12345" \
    src/open_r1/grpo.py \
    --use_vllm true \
    --output_dir ${OUTPUT_DIR} \
    --model_name_or_path ${QWEN_PATH} \
    --dataset_name ${HF_DATASET} \
    --max_prompt_length 16384 \
    --max_completion_length 768 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --learning_rate 1e-6 \
    --lr_scheduler_type "cosine" \
    --weight_decay 0.01 \
    --logging_steps 1 \
    --bf16 true \
    --gradient_checkpointing true \
    --attn_implementation flash_attention_2 \
    --min_pixels 3136 \
    --max_pixels 501760 \
    --num_train_epochs 1 \
    --run_name ${RUN_NAME} \
    --save_steps 100 \
    --save_only_model false \
    --temporal true \
    --len_control true \
    --report_to wandb \
    --beta 0.04 \
    --max_grad_norm 5 \
    --temperature 1.0 \
    --num_generations 8 \
    --vllm_device "cuda:3" \
    --vllm_gpu_memory_utilization 0.7 \
    --deepspeed ${DS_CONFIG} \
    2>&1 | tee "${OUTPUT_DIR}/training_log.txt"
```

I am using 4 A100 GPUs, where I specify CUDA_VISIBLE_DEVICES="0,1,2,3", --nproc_per_node="3", and --vllm_device "cuda:3". I get an out-of-memory error. Is this normal? My qwen_vl_utils settings are as follows:
```
IMAGE_FACTOR = 28
MIN_PIXELS = 4 * 28 * 28
MAX_PIXELS = 256 * 28 * 28
MAX_RATIO = 200

VIDEO_MIN_PIXELS = 128 * 28 * 28
VIDEO_MAX_PIXELS = 128 * 28 * 28
FRAME_FACTOR = 2
FPS = 2.0
FPS_MIN_FRAMES = 4
FPS_MAX_FRAMES = 16
```


 Error：
```
{'loss': 0.0, 'grad_norm': 2.8939287611618147, 'learning_rate': 9.99999997112166e-07, 'completion_length': 394.0833435058594, 'rewards/accuracy_reward': 0.4511299133300781, 'rewards/format_reward': 1.0, 'all_wrong': 0.0, 'all_correct': 0.3333333333333333, 'temporal_rewards': 0.5, 'reward': 1.6177966594696045, 'reward_std': 0.07210297137498856, 'kl': 0.00074005126953125, 'epoch': 0.0}
  0%|          | 3/87691 [01:33<741:07:36, 30.43s/it]qwen-vl-utils using decord to read video.
prompt_length: 425
prompt_length: 1161prompt_length:
 207
[rank2]: Traceback (most recent call last):
[rank2]:   File "/mnt/data_nas/guanfb/R1/Video-R1-main-25-4-7/src/r1-v/src/open_r1/grpo.py", line 319, in <module>
[rank2]:     main(script_args, training_args, model_args)
[rank2]:   File "/mnt/data_nas/guanfb/R1/Video-R1-main-25-4-7/src/r1-v/src/open_r1/grpo.py", line 308, in main
[rank2]:     trainer.train()
[rank2]:   File "/home/pai/envs/video-r1/lib/python3.11/site-packages/transformers/trainer.py", line 2241, in train
[rank2]:     return inner_training_loop(
[rank2]:            ^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/pai/envs/video-r1/lib/python3.11/site-packages/transformers/trainer.py", line 2548, in _inner_training_loop
[rank2]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank2]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/pai/envs/video-r1/lib/python3.11/site-packages/transformers/trainer.py", line 3698, in training_step
[rank2]:     loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/mnt/data_nas/guanfb/R1/Video-R1-main-25-4-7/src/r1-v/src/open_r1/trainer/vllm_grpo_trainer_modified.py", line 684, in compute_loss
[rank2]:     per_token_logps = self._get_per_token_logps(model, prompt_completion_ids, **prompt_inputs)
[rank2]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/mnt/data_nas/guanfb/R1/Video-R1-main-25-4-7/src/r1-v/src/open_r1/trainer/vllm_grpo_trainer_modified.py", line 426, in _get_per_token_logps
[rank2]:     log_probs = logits_row.log_softmax(dim=-1)
[rank2]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 436.00 MiB. GPU 2 has a total capacity of 79.15 GiB of which 389.69 MiB is free. Process 232717 has 78.76 GiB memory in use. Of the allocated memory 75.55 GiB is allocated by PyTorch, and 2.47 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

```

**Comment by tulerfeng** [comment]
@bingo-G Thanks for your question. This is normal.

4 A100 GPUs are not enough for run vllm training. At least 5 A100 GPUs is required.

If you want to run with 4 A100 GPUs, you can use [run_grpo_video.sh](https://github.com/tulerfeng/Video-R1/blob/main/src/scripts/run_grpo_video.sh) and reduce the default settings (e.g., set the `temporal` argument to false and decrease `num_generations`). However, running with only 4 A100 GPUs may still occasionally result in out-of-memory (OOM) errors.
